DjangoScoutingApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login
from scouting import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("scouting.urls")),
    path('logout/', logout_then_login, {'login_url': settings.LOGIN_REDIRECT_URL}, name='logout'),
    path("accounts/", include("django.contrib.auth.urls")),

]


# Serve media files during development
if settings.DEBUG:  # Only serve media files in development mode
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("scouting.urls")),
    path('logout/', logout_then_login, {'login_url': settings.LOGIN_REDIRECT_URL}, name='logout'),
    path("accounts/", include("django.contrib.auth.urls")),
]

admin.site.site_header = "Team 3637 Scouting"
admin.site.site_title = "Team 3637 Scouting"
admin.site.index_title = "Scouting administration"

scouting/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login

app_name = 'scouting'

urlpatterns = [

    path('', views.view_index, name="index"),
    path('picklist/', views.view_picklist, name='picklist'),

    path('standsscoutteam/<int:match_number>/<int:team_number>', views.view_match,
         name="stands_scout_match"),  # Changed view_match to view_stands_scout_team
    path('pitscoutteamlist', views.view_pit_scout_team_list, name="pit_scout_teams_list"),
    path('pitscoutteam/<int:team_number>', views.view_pit_scout_team, name="pit_scout_team"),
    path('scouting/teamstatistics/<int:team_number>', views.view_team_statistics, name="team_statistics"),
    path('scouting/teamstatisticslist', views.view_team_statistics_list, name="team_statistics_list"),
    path('sync/matchdata', views.sync_data, name="sync_match_data"),
    path('sync/pitdata', views.sync_data, name="sync_pit_data"),
    path('update_priority/', views.update_priority, name='update_priority')


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load git_version %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'css/select2/select2.min.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/select2/select2.full.min.js' %}"></script>

    <title>Team 3637  {% block title %}{% endblock %}</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    {% block brand %}{% endblock %}
    <!-- Hamburger menu button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible navbar -->
    <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav">
            {% block navbar_items %}{% endblock %}
            <!-- Existing Picklist link -->
            <li class="nav-item">
                <a href="{% url 'scouting:picklist' %}" class="nav-link">Picklist</a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="signinDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user mr-1"></i> {{ user.first_name }} {{ user.last_name }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="signinDropdown">
                        {% if user.is_staff %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank"><i class="fas fa-user-shield mr-3"></i>Admin</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt mr-3"></i>Sign Out</a>
                    </div>
                </li>
            {% else %}
                <li class="navbar-item">
                    <a href="{% url 'login' %}" class="nav-link">Sign In <i class="fas fa-sign-in-alt ml-1"></i></a>
                </li>
            {% endif %}
        </ul>
    </div>
    </nav>

    <main role="main">
        <!-- Content -->
        {% block content %}{% endblock %}
    </main>

    <footer class="footer {% if debug %} bg-warning {% else %} bg-secondary {% endif %} d-flex align-items-start justify-content-between">
        <div class="w-25">
            <img alt="Team 3637 Logo" src="{% static 'images/logo.png' %}" height="70px" class="ml-3 mt-3"/>
        </div>

        {% if user.is_staff and not debug %}
            <p class="mt-auto mb-3 ml-3 mr-3">{% git_version %}</p>
        {% elif debug %}
            <p class="mt-auto mb-3 ml-3 mr-3">YOU ARE RUNNING IN DEVELOPMENT MODE!</p>
        {% endif %}
    </footer>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>